update vbrowser images

diff --git a/docker/containers-update/vbrowsers/signal/root/defaults/autostart b/docker/containers-update/vbrowsers/signal/root/defaults/autostart
--- a/docker/containers-update/vbrowsers/signal/root/defaults/autostart
+++ b/docker/containers-update/vbrowsers/signal/root/defaults/autostart
@@ -5,8 +5,13 @@ signal-desktop \
    "$@" > /dev/null 2>&1
 
 PROCESS_NAME="signal-desktop"
+API_URL="https://$CUSTOM_DOMAIN/close_session/$UUID"
 
-
-
-
-
+while true; do
+    if ! pgrep -f "$PROCESS_NAME" > /dev/null; then
+        echo "Process $PROCESS_NAME not found. Sending API request."
+        curl -X POST -H "Content-Type: application/json" "$API_URL"
+        break
+    fi
+    sleep 10  # Check every 10 seconds
+done
diff --git a/docker/containers-update/vbrowsers/ungoogled/root/defaults/autostart b/docker/containers-update/vbrowsers/ungoogled/root/defaults/autostart
--- a/docker/containers-update/vbrowsers/ungoogled/root/defaults/autostart
+++ b/docker/containers-update/vbrowsers/ungoogled/root/defaults/autostart
@@ -31,8 +31,13 @@ else
 fi
 
 PROCESS_NAME="chrome"
+API_URL="https://$CUSTOM_DOMAIN/close_session/$UUID"
 
-
-
-
-
+while true; do
+    if ! pgrep -f "$PROCESS_NAME" > /dev/null; then
+        echo "Process $PROCESS_NAME not found. Sending API request."
+        curl -X POST -H "Content-Type: application/json" "$API_URL"
+        break
+    fi
+    sleep 10  # Check every 10 seconds
+done
